#ifndef EFI_PROTOCOLS_DRIVER_FAMILY_OVERRIDE_H
#define EFI_PROTOCOLS_DRIVER_FAMILY_OVERRIDE_H

#define EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL_GUID {0xb1ee129e,0xda36,0x4181, {0x91,0xf8,0x04,0xa4,0x92,0x37,0x66,0xa7}}

typedef struct _EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL;

typedef
UINT32
(EFIAPI *EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION)(
	IN EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL *This
);

typedef struct _EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL {
	EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION GetVersion;
} EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL;

#endif /* EFI_PROTOCOLS_DRIVER_FAMILY_OVERRIDE_H */
