#ifndef EFI_PROTOCOLS_DRIVER_SUPPORTED_EFI_VERSION_H
#define EFI_PROTOCOLS_DRIVER_SUPPORTED_EFI_VERSION_H

#define EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL_GUID {0x5c198761,0x16a8,0x4e69, {0x97,0x2c,0x89,0xd6,0x79,0x54,0xf8,0x1d}}

typedef struct _EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL;

typedef struct _EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL {
	UINT32 Length;
	UINT32 FirmwareVersion;
} EFI_DRIVER_SUPPORTED_EFI_VERSION_PROTOCOL;

#endif /* EFI_PROTOCOLS_DRIVER_SUPPORTED_EFI_VERSION_H */
