#ifndef EFI_PROTOCOLS_SIMPLE_FILE_SYSTEM_H
#define EFI_PROTOCOLS_SIMPLE_FILE_SYSTEM_H

#define EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_REVISION				0x00010000

typedef struct _EFI_SIMPLE_FILE_SYSTEM_PROTOCOL EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

typedef
EFI_STATUS
(EFIAPI *EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME)(
	IN EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *This,
	OUT EFI_FILE_PROTOCOL **Root
);

typedef struct _EFI_SIMPLE_FILE_SYSTEM_PROTOCOL {
	UINT64 Revision;
	EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME OpenVolume;
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

#endif /* EFI_PROTOCOLS_SIMPLE_FILE_SYSTEM_H */
